backend:
  name: git-gateway
  branch: main

media_folder: "images"

collections:
  - name: "posts"
    label: "Статьи"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Рубрика", name: "category", widget: "select", options: ["Фото", "Видео", "Мода"]}
      - {label: "Дата", name: "date", widget: "datetime"}
      - {label: "Обложка", name: "thumbnail", widget: "image"}
      - {label: "Текст статьи", name: "body", widget: "markdown"}
